name: First Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     
     - name: Run a single github action
       run: echo "This action works successfully!"
